version: '2'
networks:
  mynet:
    ipam:
      config:
        - subnet : 172.20.1.0/24
services:
  postgresql:
    image: arm64v8/postgres:15
    restart: always
    volumes:
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/data/db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

    hostname: postgresql_host
    networks:
      mynet:
        ipv4_address: 172.20.1.2
 
  odoo:
    image: jemiaymen/odoo:15
    ports:
      - '8081:8069'
    volumes:
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/dev/addons:/mnt/extra-addons'
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/data/odoo:/var/lib/odoo'
    depends_on:
      - postgresql
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo

    hostname: odoo_host
    networks:
      mynet:
        ipv4_address: 172.20.1.3

volumes:
  odoo:
    driver: local

  postgresql: 
    driver: local
