version: '2'
networks:
  mynet:
    ipam:
      config:
        - subnet : 172.20.0.0/24
services:
  mariadb:
    image: arm64v8/mariadb:10.10
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MARIADB_USER=prestashop
      - MARIADB_DATABASE=prestashop
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_PASSWORD=admin
    volumes:
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/data/mysql:/var/lib/mysql'
    hostname: mariadb_host
    networks:
      mynet:
        ipv4_address: 172.20.0.5

  prestashop:
    image: aangiel/prestashop:1.7.8.0-arm64
    ports:
      - "8080:80"
    environment:

      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=prestashop
      - PRESTASHOP_DATABASE_NAME=prestashop
      - PRESTASHOP_DATABASE_PASSWORD=admin
    hostname: prestashop_host
    networks:
      mynet:
        ipv4_address: 172.20.0.6
  
  postgresql:
    image: arm64v8/postgres:15
    restart: always
    volumes:
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/data/postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

    hostname: postgresql_host
    networks:
      mynet:
        ipv4_address: 172.20.0.2

  odoo:
    image: jemiaymen/odoo:15
    ports:
      - '8081:8069'
    volumes:
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/dev/addons:/mnt/extra-addons'
      - '/Users/jemix/Documents/projects/aisysnext_odoo_prestashop/data/odoo:/var/lib/odoo'
    depends_on:
      - postgresql
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo

    hostname: odoo_host
    networks:
      mynet:
        ipv4_address: 172.20.0.3
